/**
 * Combat Types
 *
 * File ini berisi type definitions untuk sistem combat.
 */

/**
 * Game Modes
 */
export type GameMode = "story" | "time_target" | "practice";

/**
 * Body Modes
 */
export type BodyMode = "full_body" | "half_body";

/**
 * Game Phases
 */
export type GamePhase = "idle" | "mode_select" | "calibrating" | "loading" | "playing" | "paused" | "finished";

/**
 * Tracking Status (for occlusion handling)
 */
export type TrackingStatus = "ok" | "soft_pause" | "hard_pause";

/**
 * CombatSessionStatus
 *
 * Status sesi combat.
 * - idle: Sesi belum dimulai
 * - running: Sesi sedang berjalan
 * - ended: Sesi sudah berakhir
 */
export type CombatSessionStatus = "idle" | "running" | "ended";

/**
 * Target Sequence Entry
 *
 * Definition of a single target spawn event.
 */
export interface TargetSequenceEntry {
  x_percent: number;
  y_percent: number;
  radius_percent: number;
  duration_ms: number;
  delay_ms: number;
  valid_joints: string[];
}

/**
 * GameplayData
 *
 * Full level data generated by AI or fallback presets.
 */
export interface GameplayData {
  theme: string;
  storyNarrative: string;
  target_sequence: TargetSequenceEntry[];
  expectedTotalScore: number;
}

/**
 * CombatTargetState
 *
 * State target combat.
 * - active: Target sedang aktif dan bisa dihit
 * - hit: Target berhasil dihit oleh player
 * - missed: Target terlewat (tidak dihit dalam waktu yang ditentukan)
 */
export type CombatTargetState = "active" | "hit" | "missed";

/**
 * CombatTarget
 *
 * Interface untuk target combat yang muncul di arena.
 *
 * Properties:
 * - id: Unique identifier untuk target
 * - spawnedAtMs: Timestamp saat target di-spawn (ms)
 * - expiresAtMs: Timestamp saat target akan expired (ms)
 * - state: State target saat ini (active/hit/missed)
 * - label: Label zona yang harus mengenai target (HEAD, LEFT HAND, dll)
 * - position: Posisi target dalam koordinat normalized (0-1)
 */
export interface CombatTarget {
  id: string;
  spawnedAtMs: number;
  expiresAtMs: number;
  state: CombatTargetState;
  /** Hit zone label shown on the floating AR chip (e.g. HEAD, LEFT FOOT). */
  label: string;
  position: {
    x: number;  // Koordinat X normalized (0-1)
    y: number;  // Koordinat Y normalized (0-1)
  };
}

/**
 * CombatSessionState
 *
 * Interface untuk state sesi combat.
 *
 * Properties:
 * - status: Status sesi saat ini
 * - startedAtMs: Timestamp saat sesi dimulai (null jika belum dimulai)
 * - endsAtMs: Timestamp saat sesi berakhir (null jika belum dimulai)
 * - timeLeftMs: Waktu tersisa dalam milidetik
 * - hits: Jumlah target berhasil dihit
 * - misses: Jumlah target terlewat
 * - currentStreak: Streak saat ini (jumlah hit berturut-turut)
 * - bestStreak: Streak terbaik dalam sesi
 * - score: Skor total dalam sesi
 */
export interface CombatSessionState {
  status: CombatSessionStatus;
  startedAtMs: number | null;
  endsAtMs: number | null;
  timeLeftMs: number;
  hits: number;
  misses: number;
  currentStreak: number;
  bestStreak: number;
  score: number;
}
